import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const orbSans = Orbitron({
  subsets: ["latin"],
  weight: ["600", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${orbSans.className}  antialiased`}>
        <header className="fixed  top-0 w-full">
          <Navbar />
        </header>
        <main className="min-h-[calc(100vh-70px)] mt-[70px]">{children}</main>
        <footer className="text-center">All right reserved!!!</footer>
      </body>
    </html>
  );
}
